import Footer from "@/components/footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <>
      <body>
        <main>
          {children}
        </main>       
        <footer>
          <Footer />
      </footer>
      </body>

      </>
    </html>
  );
}
